<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\login.html" />
	  <Content Remove="wwwroot\profile.html" />
	  <Content Remove="wwwroot\register.html" />
	  <Content Remove="wwwroot\upload.html" />
	</ItemGroup>

	<ItemGroup>
		<!-- EF Core base -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />

		<!-- SQL Server provider -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />

		<!-- EF tools -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<!-- Identity -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />

		<!-- Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>



	<ItemGroup>
		<None Include="wwwroot\profile.html" />
		<None Include="wwwroot\upload.html" />
		<None Include="wwwroot\register.html" />
		<None Include="wwwroot\login.html" />
		<None Include="wwwroot\index.html" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Microsoft\OpenApi\" />
		<Folder Include="wwwroot\games\0f2a127e-6a00-414b-8b93-06e5d70e824a\dino\" />
		<Folder Include="wwwroot\games\0f674a5b-b2f9-4455-97ee-1f2b0cf76ba6\mcclassic\" />
		<Folder Include="wwwroot\games\77001e2d-b595-48de-a526-43e003030923\osu\" />
		<Folder Include="wwwroot\games\8d0dfedf-e1b1-48da-84f1-f956947347cc\emulatorjs\" />
		<Folder Include="wwwroot\games\a1692880-2863-496d-9954-38f114ebca5c\superhot\" />
		<Folder Include="wwwroot\games\dda24e55-86bb-470a-8812-e7f21c645b39\doom\" />
		<Folder Include="wwwroot\games\e8e40e7c-1652-47b7-9968-a1104e080533\celeste\" />
	</ItemGroup>

</Project>
